### ISSUE TITLE
关于回调函数的疑问

### ISSUE THREAD

**Issue by dawnChen666** [umijs/umi-examples#15]
我使用dva + umi练习了一个项目，就是在dva父子组件的数据上有点疑问，我现在是通过props将函数传递给子组件，然后子组件回调将子组件中的数据交回给父组件使用，子组件不连接model，父组件连接对应model进行处理，但是我看这个例子里，子组件是直接dispatch调用父组件连接的model，在另一个umi-userdashboard例子里我看到是使用了回调，我想请问，是不是dva框架不建议使用回调这种形式来采集子组件的数据？
-----------------------------------------------------------------------------------------------------------------
还有一个问题，如果只是在组件自己的state，是不是还要经过model.reducers来修改还是说依然建议使用this.setState来修改

**Comment by xiaohuoni** [comment]
我觉得可能只是随手写的时候的差异吧

**Comment by xiaohuoni** [comment]
组件自己的state，可以使用this.setState来修改，有些从别的react引入的组件，就是这么处理的，没必要全部改成model.reducers
