### ISSUE TITLE
如何在登陆页过后修改路由

### ISSUE THREAD

**Issue by HongyanShen** [umijs/umi-examples#35]
你好，感谢你提供这样一个例子。但是我在实际尝试使用的时候发现app.js里面的钩子都是在页面启动的时候就调用的，而我们的的情况是需要用户先登录，登陆完成后再通过用户凭证去后台请求用户的路由表（估计很多用户需要运行时修改路由表的用户都会是这种情况）。这时这个例子就不是很适用了，请问一下这种情况下应该怎样做呢？

**Comment by xiaohuoni** [comment]
你好，可以参考antd-pro里的做法，https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js
在menu的model里面，你可以自由的修改
