### ISSUE TITLE
with-redux 运行报错

### ISSUE THREAD

**Issue by taichiyi** [umijs/umi-examples#36]
目录：umi-examples/with-redux/

根据文档的Getting Started依次运行报错

**Comment by taichiyi** [comment]
我想在umi2.x中使用redux而不是dva。

但是不知道怎么配置，找了文档和issues都没找到。后来找到了这个例子，可惜跑不起来.

**Comment by xiaohuoni** [comment]
@taichiyi 看看

**Comment by taichiyi** [comment]
nice @xiaohuoni
