### ISSUE TITLE
目前没有dispatch的类型声明文件吗？

### ISSUE THREAD

**Issue by zhixuanziben** [umijs/umi-examples#38]
只找到了这个，但是返回值是any，感觉不太对
![image](https://user-images.githubusercontent.com/18346513/55285291-6df0d400-53bb-11e9-8a52-3538cf5b9938.png)

**Comment by xiaohuoni** [comment]
```
export type Dispatch = <P = any, C = (payload: P) => void>(action: {
  type: string;
  payload?: P;
  callback?: C;
  [key: string]: any;
}) => any;
```
https://github.com/ant-design/ant-design-pro/blob/32318293cc05d9b276572885d38fd57c07b310d0/src/models/connect.d.ts#L49
