### ISSUE TITLE
dva/router和umi/router的区别

### ISSUE THREAD

**Issue by dawnChen666** [umijs/umi-examples#9]
我注意到在这个例子中，在dva的model里使用了dva/router的reduxRouter而不是umi/router的router，请问有什么区别么？我尝试在model中使用umi/router，会提示TypeError: Cannot read property 'type' of undefined 也就是调用dispatch时不能识别type，是这个意思么？

**Comment by xiaohuoni** [comment]
这两个参数不同吧，你可以看看

**Comment by sorrycc** [comment]
`dva/router` 返回的是 action，`umi/router` 是直接操作 history api 的。
